### ISSUE TITLE
request

### ISSUE THREAD

**Issue by MzjHarley** [YuanqingLee/ERLDK#2]
Hello，I am trying to run your code now, can you tell me how to get trainset_pair_new_justtrain_4.pkl ？

**Comment by MzjHarley** [comment]
I've gotten IEMOCAP_features_raw.pkl.

**Comment by YuanqingLee** [comment]
trainset_pair_new_justtrain_4 can be generated by running read.py.

**Comment by MzjHarley** [comment]
Thank you for your replyment !  In addition, can you tell me your version of pytorch?  I use pytorch 1.12. 0.

**Comment by MzjHarley** [comment]
I ran it and found that the model performance was poor, probably due to problems with the dataset. Can you send me the datasets involved in dqn_env_emocap.py?  
If possible, you can set up a link to Baidu's network disk and send the link to me in the form of an email.

**Comment by Really-Nice** [comment]
尊敬的作者你好 ，我也遇到相似的问题。我已经获得了IEMOCAP_features_raw.pkl文件，使用read.py生成了testset_pair.pkl和trainset_pair.pkl两个文件，在运行dqn_env_emocap.py的时候遇到了找不到trainset_pair_new_justtrain_4.pkl文件这样的问题。是trainset_pair.pkl被重新命名成了trainset_pair_new_justtrain_4.pkl，即trainset_pair.pkl==trainset_pair_new_justtrain_4.pkl，还是说trainset_pair_new_justtrain_4.pkl在read.py中的某处代码生成的？希望给予提示，非常感谢~~~~

**Comment by MzjHarley** [comment]
> 尊敬的作者你好 ，我也遇到相似的问题。我已经获得了IEMOCAP_features_raw.pkl文件，使用read.py生成了testset_pair.pkl和trainset_pair.pkl两个文件，在运行dqn_env_emocap.py的时候遇到了找不到trainset_pair_new_justtrain_4.pkl文件这样的问题。是trainset_pair.pkl被重新命名成了trainset_pair_new_justtrain_4.pkl，即trainset_pair.pkl==trainset_pair_new_justtrain_4.pkl，还是说trainset_pair_new_justtrain_4.pkl在read.py中的某处代码生成的？希望给予提示，非常感谢~~~~

give it up.

**Comment by YuanqingLee** [comment]
No, they're in different format. 'trainset_pair_new_justtrain_4.pkl' is new produced for real-time experiments. Sorry, I think this is a mistake when I revised and uploaded the codes. Let me correct it.  Thank you for point it out.

**Comment by Really-Nice** [comment]
@YuanqingLee 您好，看到您的回复真的非常感谢，希望您能尽快更新这个问题。您的文章对我的研究帮助非常大，向您致以诚挚的感谢~~

**Comment by xiaomage857** [comment]
> 我得到了 IEMOCAP_features_raw.pkl。

您好，请问如何得到IEMOCAP_features_raw.pkl

**Comment by MzjHarley** [comment]
> > 我得到了 IEMOCAP_features_raw.pkl。
> 
> 您好，请问如何得到IEMOCAP_features_raw.pkl

**Comment by MzjHarley** [comment]
情况有些复杂。给我发邮件



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 23, 2024 13:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YuanqingLee/ERLDK] request (Issue #2)




  
我得到了 IEMOCAP_features_raw.pkl。
  
您好，请问如何得到IEMOCAP_features_raw.pkl

**Comment by MzjHarley** [comment]
> > 我得到了 IEMOCAP_features_raw.pkl。
> 
> 您好，请问如何得到IEMOCAP_features_raw.pkl

你现在创建一个空白的仓库。

**Comment by xiaomage857** [comment]
> > > 我得到了 IEMOCAP_features_raw.pkl。
> > 
> > 
> > 您好，请问如何得到IEMOCAP_features_raw.pkl
> 
> 你现在创建一个空白的仓库。

谢谢回复，我刚刚创建好了

**Comment by MzjHarley** [comment]
我在你那个仓库里创建了一个issue



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 23, 2024 15:55 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [YuanqingLee/ERLDK] request (Issue #2)




    
我得到了 IEMOCAP_features_raw.pkl。
  
您好，请问如何得到IEMOCAP_features_raw.pkl
  
你现在创建一个空白的仓库。
  
谢谢回复，我刚刚创建好了
